language: node_js
node_js:
  - 12.18.2
sudo: required
dist: trusty
branches:
  only:
    - master
    - "/^feature.*$/"
    - "/^v[0-9].*$/"
git:
  depth: false

jobs:
  include:
    - stage: dev
      env:
        - NODE_ENV=development
      name: Unit test & Integration test
      script:
        - npm run lint
        - npm run test
    - stage: dev
      if: "(branch = master)"
      name: "Deploy to dev"
      script:
        - npm run test
        - npm run build -- --mode development
      after_success:
        - npm install -g firebase-tools
        - firebase deploy --token "$FIREBASE_TOKEN" -m "Build $TRAVIS_BUILD_NUMBER ; Build id $TRAVIS_BUILD_ID"
notifications:
  email:
    recipients:
      - trungdt@absoft.vn
