language: node_js
node_js:
  - 12.18.2
sudo: required
dist: trusty
branches:
  only:
    - master
    - "/^feature.*$/"
    - "/^v[0-9].*$/"
git:
  depth: false

jobs:
  include:
    - stage: dev
      env:
        - NODE_ENV=development
      name: Unit test & Integration test
      script:
        - npm run lint
        - npm run test
    - stage: dev
      if: "(branch = master)"
      name: "Deploy to dev"
      script:
        - npm run test
        - cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js
        - npm run build -- --mode development
      deploy:
        skip_cleanup: true
        provider: firebase
        project: "default"
        message: "Build: $TRAVIS_BUILD_NUMBER / Build id: $TRAVIS_BUILD_ID"
notifications:
  email:
    recipients:
      - trungdt@absoft.vn
